name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
        
    - name: Install dependencies
      run: bun install
      
    - name: Run lint
      run: bun run lint
      
    - name: Run tests
      run: bun run test
      
    - name: Build project
      run: bun run build
      
    - name: Verify build artifacts
      run: |
        test -f dist/index.js
        test -x dist/index.js
        ./dist/index.js --version