name: Release and Publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
        
    - name: Install dependencies
      run: bun install
      
    - name: Run lint
      run: bun run lint
      
    - name: Run tests
      run: bun run test
      
    - name: Build project
      run: bun run build
      
    - name: Verify build
      run: |
        test -f dist/index.js
        test -x dist/index.js
        ./dist/index.js --version
        
    - name: Setup Node.js for npm
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'
        
    - name: Publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}